### ISSUE TITLE
How do I stream the torrent to an HTML5 video tag in this ?

### ISSUE THREAD

**Issue by saru95** [mafintosh/torrent-stream#123]
I need to stream a movie to an html5 <video> tag using a stream . A jumpstart to achieve that would be appreciated.

**Comment by josejuanqm** [comment]
There are like 2 other questions here regarding this topic but I got an idea that does not uses peerflix, although maybe it has to be used... anyway i was thinking in using express to share the file via a localhost so that way we can send the file to a player like webchimera or into a simple html5 video tag (which is not convenient due to codec support) the problem with this is that the file cannot be used by several apps/modules, and that conflicts with the idea of sharing the file via express.. because you cannot use the file unless torrent-stream has finished using it.... so technically it wouldn't be streaming and more like.. hey wait till it downloads so you can use it....

sorry for my English i hope you get the idea and maybe someone or you can help me.

**Comment by josejuanqm** [comment]
i manage to get it working only with peerflix, made a child_process and redirected to localhost where the streaming piped from the cmd. make sure you don't specify where to pipe it to.. eg: "peerflix magnet:?..." that way peerflix throws the stream to localhost and doesn't open any other apps.

one issue i encounter was that because peerflix is not an executable file i couldn't use it with spawn child process. so we're not getting stdout

**Comment by jaruba** [comment]
Hey @saru95 , could you please close this issue, it has been discussed and solved here: https://github.com/mafintosh/peerflix/issues/211

@josejuanqm please check out the thread I linked, you should not use ``child_process`` to do this, also, using ``express`` is the same as making a streaming server as peerflix does.

**Comment by josejuanqm** [comment]
great @jaruba thanks!
